name: hiftapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  firebase_auth: ^3.3.5
  email_validator: ^2.0.1
  cloud_firestore: ^3.1.6
  intl: ^0.17.0
  http: ^0.13.4
  syncfusion_flutter_calendar: ^19.4.56
  cloud_functions: ^3.2.7
  cupertino_icons: ^1.0.2
  syncfusion_flutter_signaturepad: ^19.4.56
  firebase_core: 
  url_launcher: ^6.0.20
  firebase_storage: ^10.2.9
  google_sign_in: 
  google_maps_flutter: ^2.1.3
  geo_firestore_flutter: ^0.1.5
  flutter_local_notifications: ^9.4.0
  flutter_google_places:
    git:
        url: https://github.com/fluttercommunity/flutter_google_places
        ref: v0.3.2
  firebase_messaging: ^11.2.12
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  webview_flutter: ^3.0.2
  share_plus: ^4.0.4
  firebase_crashlytics: ^2.6.2
  firebase_app_check: ^0.0.6+10

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:


  uses-material-design: true

  
  assets:
    - assets/icons/

  
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700  
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 500  


