// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkWi89Sz-JLd56mj4gtZ6WPfkhMh7SV0',
    appId: '1:841268953851:android:a77f0e5d3856432649e65e',
    messagingSenderId: '841268953851',
    projectId: 'shiftapp-49795',
    storageBucket: 'shiftapp-49795.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkB6DvyTbzeK1sbqZwOgON4ZN1ebyMGCU',
    appId: '1:841268953851:ios:8769a8f5f8ce4dc349e65e',
    messagingSenderId: '841268953851',
    projectId: 'shiftapp-49795',
    storageBucket: 'shiftapp-49795.appspot.com',
    androidClientId:
        '841268953851-069mtiftopnb4dluurr3qlugglggjb3v.apps.googleusercontent.com',
    iosClientId:
        '841268953851-q75v4i7ho57nl9ifn8rv7c53qf0ja2bk.apps.googleusercontent.com',
    iosBundleId: 'com.shiftventures.shiftapp',
  );
}
